### ISSUE TITLE
We socket error with SoapyAfredi drivers

### ISSUE THREAD

**Issue by tamasp** [alexander-sholohov/SoapyAfedri#1]
I add the drivers into Openwebrx dev edition 3.0.0, it worked but i get every few minutes websocket error and then the page reload.  Is this the wrong version of Openwebrx or is something wrong

**Comment by alexander-sholohov** [comment]
Please try to test SoapyAfedri driver by running the following code in the console
`SoapySDRUtil --format=CS16 --direction=rx --rate=768000 --args="driver=afedri,address=192.168.1.41,port=61000" --channels=0`
(but replace address port)

Will it work long and stable?

**Comment by tamasp** [comment]
Sorry, i had a crash with it. I reinstalled the latest live cd from Jakob  https://s3.eu-west-1.amazonaws.com/de.dd5jfk.openwebrx.debian-live/2024-01-01-openwebrx-live-amd64.iso but in terminal he sees the Afedri but openwebrx wont let the afedri see in settings. So i cannot add the afedri. You can close this, i must look for a solution which LINUX OS works. Thanks
