### ISSUE TITLE
Discovery Issue

### ISSUE THREAD

**Issue by gvanem** [alexander-sholohov/SoapyAfedri#3]
I just built this module on Windows using MSVC and `clang-cl` ver. 17.0.1.
And have an issue with the discovery of my Afedri-SDR (on my LAN at 10.0.0.50, port 5000).
Specifically the `AfedriDiscovery::discovery()` function.

A `SoapySDRUtil.exe --find="driver=afedri"` does not work:
```
[WARNING] Afedri trying to find device
Bind error. No error
Bind error. No error
[INFO] Afedri driver: no any device found
No devices found! driver=afedri
```

I have to specifying address + port with `SoapySDRUtil.exe --find="driver=afedri,address=10.0.0.50,port=50000"`:
```
[WARNING] Afedri trying to find device
Bind error. No error
Bind error. No error
[INFO] Afedri driver: no any device found
[INFO] Afedri driver: Force try to make device for params: driver=afedri address=10.0.0.50 port=50000 bind_address=0.0.0.0 bind_port=50000 rx_mode=-1 num_channels=0 map_ch0=-1
[INFO] Afedri _num_channels=1
[INFO] Afedri device created.
[INFO] Afedri device detected: afedri :: 10.0.0.50:50000
[INFO] Afedri RX Thread: in stop_working_thread_close_socket
[INFO] Afedri RX Thread: Exit RX thread
Found device 0
  driver = afedri
  label = afedri :: 10.0.0.50:50000
  version_string = AFEDRI-SDR
```

But a `SoapySDRUtil.exe --find="driver=netsdr"` works fine:
```
Found device 0
  driver = netsdr
  label = RFspace NetSDR SN 31351F39
  name = AFEDRI-SDR
  netsdr = 10.0.0.50:50000
  serial = 31351F39
```

The above `Bind error. No error` comes from the use of `bind (488, 169.254.205.1:48322) --> WSAEADDRNOTAVAIL (10049).`
and together with `strerror(errno)`! Please use `WSAGetLastError()` for this case.

Since a Discovery AFAICS should find the remote IP/port (like the `NetSdrSupport.dll` does), why is it needed to specify it?
Not much of a Discovery process IMHO.

 `NetSdrSupport.dll` does send 2 discovery-packets:
  * one to the interface broadcast address (like `10.0.0.255:48321`) and
  * one to the global broadcast address `255.255.255.255:48321`.
  
and get a response immediately (from the latter I assume).
Your module does something else. Not sure what.

BTW, shouldn't the adapters-enumeration ignore adapters that is not up? Like:
```diff
--- a/src/utils/afedri_discovery.cpp 2024-02-21 13:25:55
+++ b/src/utils/afedri_discovery.cpp 2024-02-21 14:22:00
@@ -83,6 +83,10 @@
             {
                 continue;
             }
+            if (pCurrAddresses->OperStatus != IfOperStatusUp)
+            {
+                continue;
+            }

             for (pUnicast = pCurrAddresses->FirstUnicastAddress; pUnicast; pUnicast = pUnicast->Next)
             {
```

**Comment by alexander-sholohov** [comment]
Thank you for the found issues.
I've made changes and implement the discovery process in the same way as NetSDR does this.
Can you please test on your side.
Thank you.

**Comment by gvanem** [comment]
Works better now. A `SoapySDRUtil.exe --find="driver=afedri"` returns:
```
[WARNING] Afedri trying to find device
Found device 0
  address = 10.0.0.50
  driver = afedri
  label = afedri :: 10.0.0.50:50000
  port = 50000
  serial = 31351F39
  version_string = AFEDRI-SDR
```

after 2 sec. 

And a `SoapySDRUtil.exe --find="driver=netsdr"` returns:
```
 Found device 0
  driver = netsdr
  label = RFspace NetSDR SN 31351F39
  name = AFEDRI-SDR
  netsdr = 10.0.0.50:50000
  serial = 31351F39
```

after 640 msec! So your modules is not quite the same.

And testing `SoapySDRUtil.exe --args="driver=afedri" --rate=200000 --direction=RX`:
```
[INFO] Afedri: Set sample rate as 200000, actual sample rate will be 200000, quartz=80000000
[INFO] Afedri in setupStream. Num_channels=1, format=CS16
[INFO] Afedri: stream_id=1, actual_channels=[0], format=CS16
Stream format: CS16
Num channels: 1
Element size: 4 bytes
Begin RX rate test at 0.2 Msps
Starting stream loop, press Ctrl+C to exit...
0.185314 Msps   0.741256 MBps
0.162822 Msps   0.651288 MBps
0.195434 Msps   0.781737 MBps
0.196516 Msps   0.786064 MBps
0.197183 Msps   0.788731 MBps
0.197635 Msps   0.790541 MBps
```

The same for `netsdr` shows 2 times the `MBps`:
```
0.185232 Msps   1.48185 MBps
0.192615 Msps   1.54092 MBps
0.195075 Msps   1.5606 MBps
0.196306 Msps   1.57045 MBps
0.197044 Msps   1.57635 MBps
0.197536 Msps   1.58029 MBps
0.197888 Msps   1.5831 MBps
```

Not sure why.

**Comment by alexander-sholohov** [comment]
```
Stream format: CS16
Num channels: 1
Element size: 4 bytes
Begin RX rate test at 0.2 Msps
Starting stream loop, press Ctrl+C to exit...
0.185314 Msps   0.741256 MBps
0.162822 Msps   0.651288 MBps
```

0.2Msps * 1 channel * 4 bytes per sample = 0.8 MBps - is correct value.

Please show _Num channels_ and _Element size_ for netsdr.

**Comment by gvanem** [comment]
> Please show Num channels and Element size for netsdr.

OK:

```
F:\gv\dx-radio\SoapySDR\SoapyAfedri> SoapySDRUtil.exe --args="driver=netsdr" --rate=200000 --direction=RX
Using RFSPACE AFEDRI-SDR SN 31351F39 BOOT 1 FW 106 HW 5
getNativeStreamFormat
Stream format: CF32
Num channels: 1
Element size: 8 bytes
Begin RX rate test at 0.2 Msps
getStreamMTU
Starting stream loop, press Ctrl+C to exit...
activateStream + start 0000000000000002 0 0 0
0.185075 Msps   1.4806 MBps
0.192535 Msps   1.54028 MBps
0.195023 Msps   1.56018 MBps
0.196266 Msps   1.57013 MBps
0.197012 Msps   1.5761 MBps
0.197509 Msps   1.58008 MBps
0.197865 Msps   1.58292 MBps
0.198131 Msps   1.58505 MBps ^C
\deactivateStream
closeStream
```

Similar?

**Comment by alexander-sholohov** [comment]
Ok. netsdr has CF32  format - 8 bytes per sample, that's why netsdr has double MBps rate over CS16 format. All ok here.

Discovery problem is resolved. I close the issue.
