### ISSUE TITLE
Using 'AfedriSoapy.dll' in SDR++

### ISSUE THREAD

**Issue by gvanem** [alexander-sholohov/SoapyAfedri#4]
The `README.md` says:
> Tested with:
> OpenWebRX
> SDR++

Trying it myself; `SDRpp.exe` with `soapy_source.dll` and `AfedriSoapy.dll` has some issues. 
I built the SDR++ `soapy_source.dll` using MSVC/clang-cl and tried to use if. Selecting it here:
![sdrpp-soapy-source](https://github.com/alexander-sholohov/SoapyAfedri/assets/945271/f7d4d33f-a438-4d40-9682-256632eee93f)

wrote this to the console-screen:
```
  [WARNING] Afedri trying to find device
  [WARNING] Afedri is making device:
  [INFO] afedri_key: address - 10.0.0.50
  [INFO] afedri_key: driver - afedri
  [INFO] afedri_key: label - afedri :: 10.0.0.50:50000
  [INFO] afedri_key: port - 50000
  [INFO] afedri_key: serial - 31351F39
  [INFO] afedri_key: version_string - AFEDRI-SDR
  [INFO] Afedri driver: Making device for params: driver=afedri address=10.0.0.50 port=50000 bind_address=0.0.0.0
         bind_port=50000 rx_mode=-1 num_channels=0 map_ch0=-1
 ... <hangs, no "Afedri device created">
```

It hangs for approx. 10 sec before exiting w/o any clue.
Other times it works fine. Like in this trace:
```
  [WARNING] Afedri trying to find device
  [WARNING] Afedri is making device:
  [INFO] afedri_key: address - 10.0.0.50
  [INFO] afedri_key: driver - afedri
  [INFO] afedri_key: label - afedri :: 10.0.0.50:50000
  [INFO] afedri_key: port - 50000
  [INFO] afedri_key: serial - 31351F39
  [INFO] afedri_key: version_string - AFEDRI-SDR
  [INFO] Afedri driver: Making device for params: driver=afedri address=10.0.0.50 port=50000 bind_address=0.0.0.0
         bind_port=50000 rx_mode=-1 num_channels=0 map_ch0=-1
  [INFO] Afedri _num_channels=1
  [INFO] Afedri device created.
  [WARNING] Afedri: Set sample rate as 48000, actual sample rate will be 47962, quartz=80000000
  [INFO] Afedri in setAntenna. ch=0 name=RX
  [INFO] Afedri: setGain Name=RF, Gain=-10.000000
  [INFO] Afedri: setGain Name=FE, Gain=0.000000
  [INFO] Afedri: setGain Name=R820T_LNA_GAIN, Gain=-7.500000
  [INFO] Afedri: setGain Name=R820T_MIXER_GAIN, Gain=0.000000
  [INFO] Afedri: setGain Name=R820T_VGA_GAIN, Gain=1.000000
  [INFO] Afedri: Setting center freq. channel=0, freq=123670989
  [INFO] Afedri in setupStream. Num_channels=0, format=CF32
  [INFO] Afedri: stream_id=1, actual_channels=[0], format=CF32
  [24/02/2024 15:38:23.000] [INFO] SoapyModule 'Soapy Source': Start!
  [24/02/2024 15:38:34.000] [INFO] SoapyModule 'Soapy Source': Tune: 7631498.647217!
```

No idea what causes these hangs.

And BTW I fail to see what these `R820T*` strings has to do with my HF-version of Afedri-SDR (it has no VHF/SHF bands). 
AFAIK the R820T2 chip (like in the RTL dongles) is the Analog Font-end chip for the VHF/SHF band.

So maybe your driver can detect if the Afedri-SDR has VHF/SHF bands too?

**Comment by alexander-sholohov** [comment]
Please show output of ```SoapySDRUtil --probe="driver=afedri"``` . This is regarding detecting R820T tuner.
(The first part where "Device identification")

**Comment by gvanem** [comment]
> Please show output of SoapySDRUtil --probe="driver=afedri" . This is regarding detecting R820T tuner.

Here it is:
```
...
----------------------------------------------------
-- Device identification
----------------------------------------------------
  driver=Afedri
  hardware=AFEDRI-SDR
  diversity_mode=3
  firmware_version=00001021
  hw_fw_version=080000
  interface_version=0101
  main_clock_frequency=80000000
  origin=https://github.com/alexander-sholohov/SoapyAfedri
  product_id=SDR/3
  serial_number=31351F39
  soapy_afedri_driver_version=1.0.1
  version_string=AFEDRI-SDR

----------------------------------------------------
-- Peripheral summary
----------------------------------------------------
  Channels: 1 Rx, 0 Tx
  Timestamps: NO
  Other Settings:
     * R820T LNA AGC - R820T LNA AGC
       [key=r820t_lna_agc, default=false, type=bool]
     * R820T MIXER AGC - R820T MIXER AGC
       [key=r820t_mixer_agc, default=false, type=bool]

----------------------------------------------------
-- RX Channel 0
----------------------------------------------------
  Full-duplex: NO
  Supports AGC: NO
  Stream formats: CS16, CF32
  Native format: CS16 [full-scale=32768]
  Antennas: RX
  Full gain range: [0, 148.5] dB
    RF gain range: [-10, 35] dB
    FE gain range: [0, 12] dB
    R820T_LNA_GAIN gain range: [-7.5, 35] dB
    R820T_MIXER_GAIN gain range: [0, 2] dB
    R820T_VGA_GAIN gain range: [1, 48] dB
  Full freq range: [0.1, 35], [35, 1450] MHz
    RF freq range: [0.1, 35], [35, 1450] MHz
  Sample rates: [0.048, 2.4] MSps
  Filter bandwidths: [0, 2.4] MHz

[INFO] Afedri RX Thread: in stop_working_thread_close_socket
[INFO] Afedri RX Thread: Exit RX thread
```

My Afedri does not have a coax for for the VHF/SHF band. But looking at the above seems it supports VHF/SHF only internally!
The `[35, 1450] MHz` cannot be true.

**Comment by gvanem** [comment]
This is what I have:
![image](https://github.com/alexander-sholohov/SoapyAfedri/assets/945271/3a9a7ffa-4d74-429c-b7d8-5fa432e9acde)

**Comment by nmaster2042** [comment]
Maybe one these property could be used to know if device has 35 - 1450 Mhz Tuner ?

  diversity_mode=3
  firmware_version=00001021
  hw_fw_version=080000
  interface_version=0101
  main_clock_frequency=80000000
  product_id=SDR/3
  serial_number=31351F39

**Comment by alexander-sholohov** [comment]
These parameters are identical for devices with and without the tuner.

**Comment by alexander-sholohov** [comment]
I've added method to distinguish devices without r802t tuner.

About SDR++: I compiled latest SDR++ with MSVC toolchain. It works stable, starts each time successfully.
Can you please try with latest version SoapyAfedri and sdr++.
I'm not sure it is important - the only device I have in drop down list is my Afedri.

**Comment by gvanem** [comment]
> I've added method to distinguish devices without r802t tuner.

Much better. Now from `soapysdrutil --probe=driver=afedri`:
```
...
----------------------------------------------------
-- Peripheral summary
----------------------------------------------------
  Channels: 1 Rx, 0 Tx
  Timestamps: NO

----------------------------------------------------
-- RX Channel 0
----------------------------------------------------
  Full-duplex: NO
  Supports AGC: NO
  Stream formats: CS16, CF32
  Native format: CS16 [full-scale=32768]
  Antennas: RX
  Full gain range: [0, 57] dB
    RF gain range: [-10, 35] dB
    FE gain range: [0, 12] dB
  Full freq range: [0.1, 35] MHz
    RF freq range: [0.1, 35] MHz
  Sample rates: [0.048, 2.4] MSps
  Filter bandwidths: [0, 2.4] MHz

[INFO] Afedri RX Thread: in stop_working_thread_close_socket
[INFO] Afedri RX Thread: Exit RX thread
```

But compared to a `soapysdrutil --probe=driver=netsdr`, the `Sample rates` are more detailed and accurate:
`Sample rates: 0.02, 0.032, 0.04, 0.05, 0.08, ..., 0.625, 0.8, 1, 1.25, 2 MSps`

So I'm confused regarding what the true sample-rates / bandwidths of this Afedri is. SDR-Console shows:
![Afedri-sample-rates](https://github.com/alexander-sholohov/SoapyAfedri/assets/945271/162306f2-aea4-47c3-a67f-f8f86d63145e)

And in SDR++ with a 2.5 MBS/s sample-rate, the sound sound like shit. So I think 2.5 MBS/s is above it's limit.

Then deleting `AfedriSupport.dll` from the `%SOAPY_SDR_PLUGIN_PATH%`, SDR++ came up with `RFSPACE NetSDR`. 
It also showed some issues with hangs at exit. So my issue is probably caused by SDR++ in some way.

But I like your .DLL better; In SDR++, NetSDR has no setting for RF and FE-gain. Thanks for creating SoapyAfedri!

**Comment by alexander-sholohov** [comment]
Sample rate in Afedri can be any, so, showing it as a range [from, to] is absolutely correct way.
SDR++ uses SoapySDR API method listSampleRates() and its output is also correct for Adedri device with any internal main clock. It shows "golden" sample rates:
   
![2024-03-09_10-39-12](https://github.com/alexander-sholohov/SoapyAfedri/assets/1522531/4eabf25b-ee3a-4b9a-a8b7-755e113d18b5)

**Comment by alexander-sholohov** [comment]
I dig a little into this issue. An std::exception inside SoapySDR driver during make can cause SDR++ silent crash. @gvanem , can you please try to use module with [this](https://github.com/alexander-sholohov/SDRPlusPlus/commit/712d771952a3603c039f64929f2f591882c3020a) modifications.

**Comment by gvanem** [comment]
> can you please try to use module with [this](https://github.com/alexander-sholohov/SDRPlusPlus/commit/712d771952a3603c039f64929f2f591882c3020a) modifications.

I applied the patch to both SDR++ official and the [Sanny Sannof](https://github.com/sannysanoff/SDRPlusPlusBrown.git ) version. 
Compiles fine and seems to catch fine. But should it continue on failure:
![image](https://github.com/alexander-sholohov/SoapyAfedri/assets/945271/8c8ae218-2cea-4c88-aea1-807c509e9793)

(my SDRplay_API service seemed to be stuck).

**Comment by alexander-sholohov** [comment]
Hmm, this is not an our catch. Our catch should have output: 
_SoapyModule '...': Could not make SoapySDR device:_

**Comment by nmaster2042** [comment]
Hi. This one is about SDRPlay lib. It seems it's not related to Afedri soapy driver.

Except if their is somewhere a conflict between the 2 drivers ?

**Comment by gvanem** [comment]
>  It seems it's not related to Afedri soapy driver.

Correct. My screen-shot was another issue (fixed). SDR++ works  with all my devices now (Afedri, RTL-SDR, SDRPlay).

**Comment by alexander-sholohov** [comment]
> Hi. This one is about SDRPlay lib. It seems it's not related to Afedri soapy driver.

Yes, I understand that the latest issue from screenshot was not related to Afedri. I was hoping to catch an exception coming from SoapySDR::Device::make(). Well, I'll close the issue then.
